name: Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust: [stable, nightly]
    steps:
      - uses: actions/checkout@v6

      - name: Start RabbitMQ
        uses: getong/rabbitmq-action@v1.2
        with:
          rabbitmq user: 'guest'
          rabbitmq password: 'guest'
          rabbitmq vhost: '/'

      - name: Set RabbitMQ URL in environment
        run: echo "TEST_AMQP_URL=amqp://guest:guest@127.0.0.1:5672//" >> $GITHUB_ENV

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}

      - name: Run cargo check
        run: cargo check --all-targets --all-features

      - name: Run cargo test
        run: cargo test --all-features

      - name: Run cargo doc tests
        run: cargo test --doc
